export const recipes = [
  {
    id: "1",
    name: "Classic Chicken Pasta",
    ingredients: [
      "chicken breast",
      "pasta",
      "garlic cloves",
      "olive oil",
      "parmesan cheese",
      "salt",
      "black pepper",
    ],
    instructions: [
      "Boil water in a large pot and add a pinch of salt. Cook pasta according to package directions until al dente.",
      "While pasta cooks, season chicken breasts with salt and black pepper.",
      "Heat olive oil in a skillet over medium heat, add minced garlic, and sauté until fragrant.",
      "Add chicken and cook for 6-7 minutes per side until fully cooked.",
      "Drain pasta and toss with the cooked chicken and garlic olive oil mixture.",
      "Grate parmesan on top and serve immediately.",
    ],
  },
  {
    id: "2",
    name: "Tomato Basil Soup",
    ingredients: [
      "tomatoes",
      "onion",
      "garlic cloves",
      "fresh basil",
      "cream",
      "salt",
      "black pepper",
      "olive oil",
    ],
    instructions: [
      "Chop tomatoes, onion, and garlic.",
      "Heat olive oil in a pot and sauté onions and garlic until soft.",
      "Add chopped tomatoes and cook for 20 minutes until tender.",
      "Blend the mixture until smooth using a blender or immersion blender.",
      "Return to heat, stir in cream, and season with salt, black pepper, and fresh basil.",
      "Simmer for 5 more minutes and serve hot.",
    ],
  },
  {
    id: "3",
    name: "Veggie Stir Fry",
    ingredients: [
      "broccoli",
      "carrots",
      "soy sauce",
      "ginger",
      "garlic",
      "vegetable oil",
      "cooked rice",
      "salt",
      "pepper",
    ],
    instructions: [
      "Cook rice according to package directions and set aside.",
      "Chop broccoli and carrots into bite-sized pieces.",
      "Heat oil in a wok, add minced garlic and ginger, and sauté for 1 minute.",
      "Add vegetables and stir-fry for 5-7 minutes until tender-crisp.",
      "Add soy sauce, salt, and pepper to taste.",
      "Serve stir-fried vegetables over rice.",
    ],
  },
  {
    id: "4",
    name: "Beef Tacos",
    ingredients: [
      "ground beef",
      "taco shells",
      "lettuce",
      "cheese",
      "salsa",
      "taco seasoning",
      "salt",
      "pepper",
    ],
    instructions: [
      "Preheat oven to 350°F (175°C) to warm taco shells.",
      "Brown ground beef in a skillet over medium heat.",
      "Add taco seasoning, a pinch of salt, and pepper. Stir well and cook for 5 minutes.",
      "Place taco shells in the oven for 5 minutes to warm.",
      "Fill each shell with cooked beef, shredded lettuce, cheese, and salsa.",
      "Serve immediately while warm.",
    ],
  },
  {
    id: "5",
    name: "Mushroom Risotto",
    ingredients: [
      "arborio rice",
      "mushrooms",
      "onion",
      "white wine",
      "vegetable broth",
      "parmesan",
      "butter",
      "olive oil",
      "salt",
      "pepper",
    ],
    instructions: [
      "Heat olive oil and butter in a pan. Sauté chopped onions and mushrooms until golden brown.",
      "Add arborio rice and toast for 2 minutes while stirring.",
      "Pour in white wine and let it absorb into the rice.",
      "Gradually add warm vegetable broth, one ladle at a time, stirring constantly.",
      "Continue adding broth until rice is creamy and cooked through.",
      "Stir in parmesan cheese, season with salt and pepper, and serve hot.",
    ],
  },
  {
    id: "6",
    name: "Greek Salad",
    ingredients: [
      "cucumber",
      "tomatoes",
      "feta cheese",
      "olives",
      "olive oil",
      "oregano",
      "salt",
      "pepper",
    ],
    instructions: [
      "Chop cucumber and tomatoes into bite-sized pieces.",
      "Combine chopped vegetables with olives in a salad bowl.",
      "Crumble feta cheese on top.",
      "Drizzle with olive oil, sprinkle oregano, salt, and pepper.",
      "Toss gently and serve immediately.",
    ],
  },
  {
    id: "7",
    name: "Salmon with Lemon",
    ingredients: [
      "salmon fillets",
      "lemon",
      "butter",
      "garlic cloves",
      "fresh dill",
      "salt",
      "pepper",
    ],
    instructions: [
      "Season salmon fillets with salt and pepper.",
      "Heat butter in a skillet over medium heat and sauté minced garlic for 1 minute.",
      "Add salmon fillets, skin-side down, and cook for 4-5 minutes per side until fully cooked.",
      "Squeeze fresh lemon juice over salmon and garnish with chopped dill.",
      "Serve immediately.",
    ],
  },
  {
    id: "8",
    name: "Egg Fried Rice",
    ingredients: [
      "cooked rice",
      "eggs",
      "peas",
      "carrots",
      "soy sauce",
      "vegetable oil",
      "salt",
      "pepper",
    ],
    instructions: [
      "Heat oil in a wok or skillet.",
      "Scramble eggs in the pan and remove once cooked.",
      "Add diced carrots and peas, sauté for 2-3 minutes.",
      "Add cold cooked rice and stir-fry for 5 minutes.",
      "Return scrambled eggs to the pan and add soy sauce, salt, and pepper.",
      "Mix well and serve hot.",
    ],
  },
  {
    id: "9",
    name: "Margherita Pizza",
    ingredients: [
      "pizza dough",
      "tomatoes",
      "mozzarella cheese",
      "basil leaves",
      "olive oil",
      "salt",
    ],
    instructions: [
      "Preheat oven to 450°F (230°C).",
      "Roll out pizza dough on a baking sheet or pizza stone.",
      "Brush dough with olive oil and sprinkle a pinch of salt.",
      "Add sliced tomatoes and mozzarella cheese on top.",
      "Bake for 12-15 minutes until crust is golden and cheese is melted.",
      "Garnish with fresh basil leaves and serve hot.",
    ],
  },
  {
    id: "10",
    name: "Chicken Curry",
    ingredients: [
      "chicken pieces",
      "curry powder",
      "coconut milk",
      "onion",
      "garlic",
      "vegetable oil",
      "rice",
      "salt",
      "pepper",
    ],
    instructions: [
      "Cook rice according to package directions and set aside.",
      "Heat oil in a pan, sauté chopped onions and garlic until soft.",
      "Add chicken pieces and brown on all sides.",
      "Add curry powder, coconut milk, salt, and pepper. Stir well.",
      "Simmer for 15-20 minutes until chicken is fully cooked.",
      "Serve chicken curry over cooked rice.",
    ],
  },
  {
    id: "11",
    name: "Avocado Toast",
    ingredients: [
      "bread slices",
      "ripe avocado",
      "lemon juice",
      "eggs",
      "salt",
      "black pepper",
      "olive oil",
    ],
    instructions: [
      "Toast bread slices until golden and crispy.",
      "Mash avocado with lemon juice, salt, and pepper.",
      "Spread avocado evenly on toast.",
      "Fry eggs to your preferred doneness and place on top of avocado.",
      "Drizzle with olive oil and serve immediately.",
    ],
  },
  {
    id: "12",
    name: "Pancakes",
    ingredients: [
      "flour",
      "eggs",
      "milk",
      "butter",
      "maple syrup",
      "baking powder",
      "salt",
      "sugar",
    ],
    instructions: [
      "In a bowl, mix flour, baking powder, sugar, and salt.",
      "In another bowl, whisk eggs and milk together.",
      "Combine wet and dry ingredients to form a smooth batter.",
      "Heat butter in a pan over medium heat. Pour batter to form pancakes.",
      "Cook 2-3 minutes per side until golden brown.",
      "Stack pancakes and drizzle with maple syrup before serving.",
    ],
  },
  {
    id: "13",
    name: "Shrimp Scampi",
    ingredients: [
      "shrimp",
      "garlic cloves",
      "butter",
      "white wine",
      "pasta",
      "parsley",
      "lemon juice",
      "salt",
      "pepper",
    ],
    instructions: [
      "Cook pasta according to package directions.",
      "Melt butter in a skillet and sauté minced garlic for 1-2 minutes.",
      "Add shrimp, salt, and pepper, and cook until pink.",
      "Pour in white wine and simmer for 2 minutes.",
      "Toss pasta with shrimp mixture and sprinkle parsley and lemon juice before serving.",
    ],
  },
  {
    id: "14",
    name: "Caprese Sandwich",
    ingredients: [
      "bread slices",
      "mozzarella cheese",
      "tomatoes",
      "basil leaves",
      "balsamic vinegar",
      "olive oil",
      "salt",
      "pepper",
    ],
    instructions: [
      "Slice mozzarella and tomatoes evenly.",
      "Layer mozzarella and tomato slices on bread slices.",
      "Add fresh basil leaves and drizzle with olive oil and balsamic vinegar.",
      "Season with salt and pepper.",
      "Close sandwich and serve immediately.",
    ],
  },
  {
    id: "15",
    name: "Chocolate Chip Cookies",
    ingredients: [
      "flour",
      "butter",
      "sugar",
      "brown sugar",
      "eggs",
      "vanilla extract",
      "chocolate chips",
      "baking soda",
      "salt",
    ],
    instructions: [
      "Preheat oven to 350°F (175°C).",
      "Cream together butter, sugar, and brown sugar until fluffy.",
      "Add eggs and vanilla extract, mix well.",
      "Stir in flour, baking soda, and salt until combined.",
      "Fold in chocolate chips.",
      "Drop spoonfuls of dough on a baking sheet and bake for 10-12 minutes until golden brown.",
    ],
  },
  {
    id: "16",
    name: "Pulled Pork Sandwich",
    ingredients: [
      "pork shoulder",
      "bbq sauce",
      "bread rolls",
      "coleslaw",
      "onion",
      "salt",
      "pepper",
    ],
    instructions: [
      "Season pork with salt and pepper.",
      "Slow cook pork with BBQ sauce for 6-8 hours until tender.",
      "Shred pork with forks and mix with remaining BBQ sauce.",
      "Serve on toasted bread rolls with coleslaw and sliced onions.",
    ],
  },
  {
    id: "17",
    name: "Caesar Salad",
    ingredients: [
      "romaine lettuce",
      "parmesan cheese",
      "croutons",
      "caesar dressing",
      "lemon juice",
      "salt",
      "pepper",
    ],
    instructions: [
      "Chop romaine lettuce into bite-sized pieces.",
      "In a large bowl, toss lettuce with Caesar dressing and lemon juice.",
      "Add parmesan cheese shavings and croutons on top.",
      "Season with salt and pepper to taste and serve immediately.",
    ],
  },
  {
    id: "18",
    name: "Thai Green Curry",
    ingredients: [
      "chicken breast",
      "green curry paste",
      "coconut milk",
      "bell peppers",
      "vegetable oil",
      "rice",
      "salt",
    ],
    instructions: [
      "Cook rice according to package instructions.",
      "Heat oil in a pan and sauté green curry paste for 1 minute.",
      "Add chicken pieces and cook until slightly browned.",
      "Pour in coconut milk and add sliced bell peppers.",
      "Simmer for 15 minutes until chicken is cooked and vegetables are tender.",
      "Serve curry over rice.",
    ],
  },
  {
    id: "19",
    name: "French Toast",
    ingredients: [
      "bread slices",
      "eggs",
      "milk",
      "cinnamon powder",
      "butter",
      "maple syrup",
      "salt",
    ],
    instructions: [
      "Whisk eggs, milk, cinnamon, and a pinch of salt in a bowl.",
      "Dip bread slices into egg mixture until fully coated.",
      "Heat butter in a pan over medium heat and cook bread slices 2-3 minutes per side until golden.",
      "Serve hot with maple syrup.",
    ],
  },
  {
    id: "20",
    name: "Spinach Quiche",
    ingredients: [
      "pie crust",
      "eggs",
      "spinach",
      "cheese",
      "cream",
      "salt",
      "pepper",
      "nutmeg",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C) and press pie crust into a quiche pan.",
      "Cook spinach until wilted and squeeze out excess water.",
      "In a bowl, whisk eggs, cream, cheese, salt, pepper, and a pinch of nutmeg.",
      "Add spinach to egg mixture and pour into crust.",
      "Bake for 35-40 minutes until set and golden on top.",
      "Allow to cool slightly before slicing and serving.",
    ],
  },
  {
    id: "21",
    name: "Spaghetti Carbonara",
    ingredients: [
      "spaghetti",
      "eggs",
      "bacon",
      "parmesan cheese",
      "black pepper",
      "salt",
      "olive oil",
    ],
    instructions: [
      "Cook spaghetti in salted boiling water until al dente.",
      "While pasta cooks, dice bacon and fry in a pan with a little olive oil until crispy.",
      "In a bowl, whisk eggs and grated parmesan together.",
      "Drain spaghetti, reserving ½ cup of pasta water.",
      "Quickly toss hot spaghetti with egg-parmesan mixture and crispy bacon. Add pasta water as needed for creaminess.",
      "Season with black pepper and serve immediately.",
    ],
  },
  {
    id: "22",
    name: "Chicken Fajitas",
    ingredients: [
      "chicken breast",
      "bell peppers",
      "onion",
      "tortillas",
      "fajita seasoning",
      "olive oil",
      "salt",
      "pepper",
    ],
    instructions: [
      "Slice chicken, bell peppers, and onion into thin strips.",
      "Heat olive oil in a skillet over medium heat.",
      "Add chicken and season with fajita seasoning, salt, and pepper. Cook until browned and cooked through.",
      "Add vegetables and sauté for 5 minutes until slightly tender.",
      "Warm tortillas in a pan or microwave.",
      "Serve chicken and vegetables in tortillas.",
    ],
  },
  {
    id: "23",
    name: "Vegetable Lasagna",
    ingredients: [
      "lasagna noodles",
      "tomato sauce",
      "zucchini",
      "spinach",
      "ricotta cheese",
      "mozzarella cheese",
      "olive oil",
      "salt",
      "pepper",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "Slice zucchini thinly and sauté with olive oil for 3-4 minutes.",
      "Boil lasagna noodles until al dente and drain.",
      "Layer a baking dish with tomato sauce, noodles, ricotta, sautéed zucchini, spinach, and mozzarella.",
      "Repeat layers until ingredients are finished, ending with mozzarella on top.",
      "Bake for 35-40 minutes until cheese is golden and bubbly.",
      "Let rest 10 minutes before serving.",
    ],
  },
  {
    id: "24",
    name: "Beef Stroganoff",
    ingredients: [
      "beef strips",
      "mushrooms",
      "onion",
      "sour cream",
      "beef broth",
      "butter",
      "flour",
      "egg noodles",
      "salt",
      "pepper",
    ],
    instructions: [
      "Cook egg noodles according to package directions and set aside.",
      "Melt butter in a skillet and sauté onions and mushrooms until tender.",
      "Add beef strips and cook until browned.",
      "Sprinkle flour over beef mixture and stir for 1 minute.",
      "Add beef broth gradually, stirring until sauce thickens.",
      "Remove from heat, stir in sour cream, season with salt and pepper.",
      "Serve beef stroganoff over noodles.",
    ],
  },
  {
    id: "25",
    name: "Lemon Garlic Shrimp",
    ingredients: [
      "shrimp",
      "garlic cloves",
      "butter",
      "lemon juice",
      "parsley",
      "salt",
      "pepper",
    ],
    instructions: [
      "Peel and devein shrimp if needed.",
      "Melt butter in a skillet and sauté minced garlic for 1 minute.",
      "Add shrimp and cook 2-3 minutes per side until pink and opaque.",
      "Squeeze fresh lemon juice over shrimp and season with salt and pepper.",
      "Garnish with chopped parsley and serve immediately.",
    ],
  },
  {
    id: "26",
    name: "Quinoa Salad",
    ingredients: [
      "quinoa",
      "cucumber",
      "tomatoes",
      "feta cheese",
      "olive oil",
      "lemon juice",
      "salt",
      "pepper",
      "fresh parsley",
    ],
    instructions: [
      "Cook quinoa according to package directions and let cool.",
      "Chop cucumber, tomatoes, and parsley.",
      "In a large bowl, combine quinoa, vegetables, and crumbled feta cheese.",
      "Drizzle with olive oil and lemon juice, season with salt and pepper.",
      "Toss gently and serve chilled or at room temperature.",
    ],
  },
  {
    id: "27",
    name: "Buffalo Chicken Wings",
    ingredients: [
      "chicken wings",
      "hot sauce",
      "butter",
      "garlic powder",
      "salt",
      "pepper",
      "celery sticks",
    ],
    instructions: [
      "Preheat oven to 400°F (200°C).",
      "Season wings with salt, pepper, and garlic powder.",
      "Bake wings on a tray for 40-45 minutes until crispy, turning halfway through.",
      "In a small saucepan, melt butter and mix with hot sauce.",
      "Toss baked wings in the sauce until evenly coated.",
      "Serve with celery sticks on the side.",
    ],
  },
  {
    id: "28",
    name: "Pesto Pasta",
    ingredients: [
      "pasta",
      "basil leaves",
      "parmesan cheese",
      "pine nuts",
      "olive oil",
      "garlic cloves",
      "salt",
      "pepper",
    ],
    instructions: [
      "Cook pasta according to package directions until al dente.",
      "In a food processor, blend basil leaves, garlic, pine nuts, and parmesan cheese.",
      "Slowly add olive oil while blending to form a smooth pesto sauce.",
      "Toss pasta with pesto and season with salt and pepper to taste.",
      "Serve immediately, garnished with extra parmesan.",
    ],
  },
  {
    id: "29",
    name: "Berry Smoothie",
    ingredients: [
      "strawberries",
      "blueberries",
      "banana",
      "yogurt",
      "honey",
      "ice cubes",
    ],
    instructions: [
      "Wash berries thoroughly and slice banana.",
      "Place all ingredients in a blender: strawberries, blueberries, banana, yogurt, honey, and ice cubes.",
      "Blend until smooth and creamy.",
      "Pour into glasses and serve chilled.",
    ],
  },
  {
    id: "30",
    name: "Chicken Alfredo",
    ingredients: [
      "fettuccine pasta",
      "chicken breast",
      "heavy cream",
      "parmesan cheese",
      "butter",
      "garlic cloves",
      "salt",
      "pepper",
      "olive oil",
    ],
    instructions: [
      "Cook fettuccine pasta according to package instructions.",
      "Season chicken with salt and pepper and cook in olive oil until golden and cooked through. Slice thinly.",
      "In a pan, melt butter and sauté minced garlic for 1 minute.",
      "Add heavy cream and simmer for 3-4 minutes.",
      "Stir in parmesan cheese until sauce thickens.",
      "Toss pasta with Alfredo sauce and top with sliced chicken before serving.",
    ],
  },
  {
    id: "31",
    name: "Vegetable Curry",
    ingredients: [
      "potatoes",
      "carrots",
      "peas",
      "onion",
      "coconut milk",
      "curry powder",
      "garlic",
      "ginger",
      "salt",
      "oil",
    ],
    instructions: [
      "Chop all vegetables into bite-sized pieces.",
      "Heat oil in a pan, sauté onions, garlic, and ginger until fragrant.",
      "Add curry powder and cook for 1 minute.",
      "Add vegetables and stir to coat with spices.",
      "Pour in coconut milk, bring to simmer, cover, and cook 15-20 minutes until vegetables are tender.",
      "Serve hot with rice.",
    ],
  },
  {
    id: "32",
    name: "Teriyaki Chicken",
    ingredients: [
      "chicken thighs",
      "soy sauce",
      "brown sugar",
      "garlic",
      "ginger",
      "cornstarch",
      "vegetable oil",
      "green onions",
    ],
    instructions: [
      "Mix soy sauce, brown sugar, minced garlic, and ginger to make teriyaki sauce.",
      "Heat oil in a skillet and cook chicken until browned and cooked through.",
      "Pour sauce over chicken and simmer for 5 minutes.",
      "Mix cornstarch with a little water and add to pan to thicken sauce.",
      "Garnish with sliced green onions and serve.",
    ],
  },
  {
    id: "33",
    name: "Stuffed Bell Peppers",
    ingredients: [
      "bell peppers",
      "ground beef",
      "rice",
      "onion",
      "tomato sauce",
      "cheese",
      "salt",
      "pepper",
      "olive oil",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "Cut tops off bell peppers and remove seeds.",
      "Cook ground beef with chopped onions until browned.",
      "Mix beef with cooked rice and season with salt and pepper.",
      "Stuff mixture into bell peppers, top with tomato sauce and cheese.",
      "Bake for 25-30 minutes until peppers are tender and cheese is melted.",
    ],
  },
  {
    id: "34",
    name: "Garlic Butter Mushrooms",
    ingredients: [
      "mushrooms",
      "butter",
      "garlic cloves",
      "parsley",
      "salt",
      "pepper",
    ],
    instructions: [
      "Clean mushrooms and slice if large.",
      "Melt butter in a skillet and sauté minced garlic for 1 minute.",
      "Add mushrooms and cook until golden brown, stirring occasionally.",
      "Season with salt and pepper and garnish with chopped parsley.",
      "Serve as a side dish.",
    ],
  },
  {
    id: "35",
    name: "Baked Ziti",
    ingredients: [
      "ziti pasta",
      "tomato sauce",
      "ricotta cheese",
      "mozzarella cheese",
      "parmesan cheese",
      "olive oil",
      "garlic",
      "salt",
      "pepper",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "Cook ziti pasta according to package directions and drain.",
      "Heat olive oil and sauté minced garlic briefly, then mix with tomato sauce.",
      "Layer pasta, ricotta, tomato sauce, and mozzarella in a baking dish.",
      "Top with parmesan and bake for 25-30 minutes until golden.",
      "Serve hot.",
    ],
  },
  {
    id: "36",
    name: "Chicken Teriyaki Stir Fry",
    ingredients: [
      "chicken breast",
      "broccoli",
      "carrots",
      "bell peppers",
      "soy sauce",
      "honey",
      "garlic",
      "ginger",
      "olive oil",
    ],
    instructions: [
      "Slice chicken and vegetables into thin strips.",
      "Mix soy sauce, honey, minced garlic, and ginger to make sauce.",
      "Heat oil in a skillet or wok, cook chicken until nearly done.",
      "Add vegetables and stir-fry for 5-6 minutes.",
      "Pour sauce over chicken and vegetables, cook 2 more minutes.",
      "Serve hot over rice or noodles.",
    ],
  },
  {
    id: "37",
    name: "Omelette with Vegetables",
    ingredients: [
      "eggs",
      "milk",
      "bell peppers",
      "onion",
      "spinach",
      "cheese",
      "salt",
      "pepper",
      "butter",
    ],
    instructions: [
      "Beat eggs with a splash of milk, salt, and pepper.",
      "Heat butter in a skillet and sauté chopped vegetables until tender.",
      "Pour eggs over vegetables and cook on medium heat until edges set.",
      "Sprinkle cheese on top and fold omelette in half.",
      "Cook 1-2 more minutes and serve immediately.",
    ],
  },
  {
    id: "38",
    name: "Shrimp Fried Rice",
    ingredients: [
      "shrimp",
      "cooked rice",
      "eggs",
      "peas",
      "carrots",
      "soy sauce",
      "vegetable oil",
      "garlic",
      "green onions",
    ],
    instructions: [
      "Heat oil in a skillet or wok and sauté minced garlic.",
      "Add shrimp and cook until pink, then remove and set aside.",
      "Add beaten eggs and scramble, then mix in cooked rice, peas, and carrots.",
      "Return shrimp to the pan, add soy sauce, and stir-fry for 3-4 minutes.",
      "Garnish with sliced green onions and serve hot.",
    ],
  },
  {
    id: "39",
    name: "Baked Salmon with Herbs",
    ingredients: [
      "salmon fillets",
      "olive oil",
      "lemon",
      "garlic",
      "thyme",
      "rosemary",
      "salt",
      "pepper",
    ],
    instructions: [
      "Preheat oven to 400°F (200°C).",
      "Place salmon fillets on a baking sheet lined with parchment paper.",
      "Drizzle with olive oil, squeeze lemon juice, sprinkle minced garlic, thyme, rosemary, salt, and pepper.",
      "Bake for 12-15 minutes until salmon is cooked through.",
      "Serve with lemon wedges.",
    ],
  },
  {
    id: "40",
    name: "Classic BLT Sandwich",
    ingredients: [
      "bread slices",
      "bacon",
      "lettuce",
      "tomato",
      "mayonnaise",
      "salt",
      "pepper",
    ],
    instructions: [
      "Cook bacon until crispy and drain on paper towels.",
      "Toast bread slices lightly.",
      "Spread mayonnaise on each slice.",
      "Layer lettuce, tomato slices, and bacon on one slice of bread.",
      "Top with the other slice of bread, cut in half, and serve.",
    ],
  },
  {
    id: "41",
    name: "Beef and Broccoli Stir Fry",
    ingredients: [
      "beef strips",
      "broccoli florets",
      "soy sauce",
      "garlic",
      "ginger",
      "cornstarch",
      "vegetable oil",
      "salt",
      "pepper",
    ],
    instructions: [
      "Mix soy sauce, cornstarch, and a little water to make a sauce.",
      "Heat oil in a wok over medium-high heat.",
      "Add beef and cook until browned, then remove from the wok.",
      "Add garlic and ginger, sauté 1 minute, then add broccoli and stir-fry 3-4 minutes.",
      "Return beef to the wok, pour sauce over, and stir until thickened.",
      "Season with salt and pepper and serve hot.",
    ],
  },
  {
    id: "42",
    name: "Chicken Parmesan",
    ingredients: [
      "chicken breast",
      "breadcrumbs",
      "parmesan cheese",
      "mozzarella cheese",
      "egg",
      "flour",
      "tomato sauce",
      "olive oil",
      "salt",
      "pepper",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "Flatten chicken breasts, season with salt and pepper.",
      "Dredge chicken in flour, dip in beaten egg, then coat with breadcrumbs mixed with parmesan.",
      "Heat olive oil in a pan and fry chicken until golden brown on both sides.",
      "Place chicken in a baking dish, top with tomato sauce and mozzarella cheese.",
      "Bake for 20-25 minutes until cheese melts and chicken is cooked through.",
    ],
  },
  {
    id: "43",
    name: "Vegetable Fried Noodles",
    ingredients: [
      "noodles",
      "carrots",
      "bell peppers",
      "cabbage",
      "soy sauce",
      "garlic",
      "ginger",
      "vegetable oil",
      "green onions",
      "salt",
      "pepper",
    ],
    instructions: [
      "Cook noodles according to package instructions and drain.",
      "Heat oil in a wok and sauté minced garlic and ginger for 1 minute.",
      "Add chopped vegetables and stir-fry for 5-6 minutes.",
      "Add noodles and soy sauce, tossing to combine.",
      "Season with salt and pepper, garnish with sliced green onions, and serve hot.",
    ],
  },
  {
    id: "44",
    name: "Grilled Cheese Sandwich",
    ingredients: ["bread slices", "cheddar cheese", "butter"],
    instructions: [
      "Heat a skillet over medium heat.",
      "Butter one side of each bread slice.",
      "Place one slice, butter side down, on the skillet, top with cheese, then another slice of bread butter side up.",
      "Cook until golden brown, flip, and cook the other side until cheese is melted.",
      "Serve immediately.",
    ],
  },
  {
    id: "45",
    name: "Chicken Noodle Soup",
    ingredients: [
      "chicken breast",
      "carrots",
      "celery",
      "onion",
      "garlic",
      "egg noodles",
      "chicken broth",
      "salt",
      "pepper",
      "parsley",
    ],
    instructions: [
      "In a pot, heat oil and sauté onions, garlic, carrots, and celery for 5 minutes.",
      "Add chicken breast and chicken broth, bring to a boil.",
      "Reduce heat and simmer 20 minutes until chicken is cooked.",
      "Remove chicken, shred it, and return to the pot.",
      "Add egg noodles and cook according to package instructions.",
      "Season with salt, pepper, and garnish with parsley before serving.",
    ],
  },
  {
    id: "46",
    name: "Stuffed Zucchini Boats",
    ingredients: [
      "zucchini",
      "ground beef",
      "tomato sauce",
      "onion",
      "garlic",
      "mozzarella cheese",
      "olive oil",
      "salt",
      "pepper",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "Cut zucchini in half lengthwise and scoop out the center to create a boat.",
      "Sauté onion, garlic, and ground beef until cooked.",
      "Add tomato sauce and season with salt and pepper.",
      "Fill zucchini boats with meat mixture and top with mozzarella cheese.",
      "Bake for 20-25 minutes until zucchini is tender and cheese is melted.",
    ],
  },
  {
    id: "47",
    name: "Beef Chili",
    ingredients: [
      "ground beef",
      "kidney beans",
      "tomato paste",
      "onion",
      "garlic",
      "chili powder",
      "cumin",
      "salt",
      "pepper",
      "olive oil",
    ],
    instructions: [
      "Heat olive oil in a large pot and sauté onions and garlic until soft.",
      "Add ground beef and cook until browned.",
      "Add tomato paste, kidney beans, chili powder, cumin, salt, and pepper.",
      "Simmer for 30-40 minutes, stirring occasionally.",
      "Serve hot, optionally with shredded cheese or sour cream.",
    ],
  },
  {
    id: "48",
    name: "Caprese Salad",
    ingredients: [
      "tomatoes",
      "mozzarella cheese",
      "basil leaves",
      "olive oil",
      "balsamic glaze",
      "salt",
      "pepper",
    ],
    instructions: [
      "Slice tomatoes and mozzarella cheese into even slices.",
      "Arrange alternating slices of tomato and mozzarella on a plate.",
      "Tuck fresh basil leaves between slices.",
      "Drizzle olive oil and balsamic glaze on top.",
      "Season with salt and pepper and serve immediately.",
    ],
  },
  {
    id: "49",
    name: "Teriyaki Salmon",
    ingredients: [
      "salmon fillets",
      "soy sauce",
      "honey",
      "garlic",
      "ginger",
      "olive oil",
      "lemon",
    ],
    instructions: [
      "Preheat oven to 400°F (200°C).",
      "Mix soy sauce, honey, minced garlic, and ginger to make teriyaki sauce.",
      "Place salmon on a baking sheet and brush with sauce.",
      "Bake for 12-15 minutes until salmon is cooked through.",
      "Serve with a squeeze of lemon.",
    ],
  },
  {
    id: "50",
    name: "Eggplant Parmesan",
    ingredients: [
      "eggplant",
      "breadcrumbs",
      "parmesan cheese",
      "mozzarella cheese",
      "tomato sauce",
      "egg",
      "flour",
      "olive oil",
      "salt",
      "pepper",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "Slice eggplant and sprinkle with salt to remove excess moisture for 30 minutes, then pat dry.",
      "Dredge eggplant in flour, dip in beaten egg, and coat with breadcrumbs mixed with parmesan.",
      "Fry eggplant slices in olive oil until golden.",
      "Layer eggplant, tomato sauce, and mozzarella in a baking dish.",
      "Bake for 20-25 minutes until cheese melts and golden brown.",
    ],
  },
  {
    id: "51",
    name: "Chicken Tikka Masala",
    ingredients: [
      "chicken breast",
      "yogurt",
      "garam masala",
      "tomato puree",
      "cream",
      "garlic",
      "ginger",
      "onion",
      "vegetable oil",
      "salt",
    ],
    instructions: [
      "Marinate chicken in yogurt, garlic, ginger, and garam masala for at least 1 hour.",
      "Heat oil in a skillet and sauté chopped onions until golden.",
      "Add marinated chicken and cook until slightly browned.",
      "Add tomato puree and simmer 15 minutes.",
      "Stir in cream and cook for 5 more minutes.",
      "Serve hot with rice or naan.",
    ],
  },
  {
    id: "52",
    name: "Shrimp Tacos",
    ingredients: [
      "shrimp",
      "taco shells",
      "cabbage",
      "lime",
      "cilantro",
      "sour cream",
      "garlic",
      "paprika",
      "salt",
      "pepper",
      "olive oil",
    ],
    instructions: [
      "Season shrimp with garlic, paprika, salt, and pepper.",
      "Heat olive oil in a skillet and cook shrimp until pink and opaque.",
      "Warm taco shells in a pan or oven.",
      "Fill tacos with shrimp, shredded cabbage, and drizzle with sour cream.",
      "Garnish with chopped cilantro and a squeeze of lime juice.",
    ],
  },
  {
    id: "53",
    name: "Spinach and Feta Omelette",
    ingredients: [
      "eggs",
      "spinach",
      "feta cheese",
      "milk",
      "salt",
      "pepper",
      "butter",
    ],
    instructions: [
      "Beat eggs with a splash of milk, salt, and pepper.",
      "Heat butter in a skillet and sauté spinach until wilted.",
      "Pour eggs over spinach and cook on medium heat until partially set.",
      "Sprinkle feta cheese on top and fold omelette in half.",
      "Cook 1-2 minutes more and serve.",
    ],
  },
  {
    id: "54",
    name: "Vegetable Soup",
    ingredients: [
      "carrots",
      "celery",
      "onion",
      "potatoes",
      "green beans",
      "tomato paste",
      "vegetable broth",
      "garlic",
      "salt",
      "pepper",
      "olive oil",
    ],
    instructions: [
      "Heat olive oil in a large pot, sauté onions, garlic, carrots, and celery for 5 minutes.",
      "Add potatoes, green beans, tomato paste, and vegetable broth.",
      "Bring to a boil, then simmer 25-30 minutes until vegetables are tender.",
      "Season with salt and pepper and serve hot.",
    ],
  },
  {
    id: "55",
    name: "Garlic Butter Chicken",
    ingredients: [
      "chicken breast",
      "garlic",
      "butter",
      "olive oil",
      "salt",
      "pepper",
      "parsley",
    ],
    instructions: [
      "Season chicken with salt and pepper.",
      "Heat olive oil and butter in a skillet over medium heat.",
      "Add minced garlic and sauté 1 minute.",
      "Cook chicken until golden brown and fully cooked, 6-7 minutes per side.",
      "Garnish with chopped parsley and serve.",
    ],
  },
  {
    id: "56",
    name: "Cheeseburger",
    ingredients: [
      "ground beef",
      "burger buns",
      "cheddar cheese",
      "lettuce",
      "tomato",
      "onion",
      "ketchup",
      "mustard",
      "salt",
      "pepper",
      "oil",
    ],
    instructions: [
      "Season ground beef with salt and pepper and form patties.",
      "Heat oil in a skillet and cook patties to desired doneness.",
      "Place cheddar cheese on patties during last minute of cooking to melt.",
      "Toast burger buns lightly.",
      "Assemble burgers with lettuce, tomato, onion, patties, and condiments.",
    ],
  },
  {
    id: "57",
    name: "Pasta Primavera",
    ingredients: [
      "pasta",
      "zucchini",
      "bell peppers",
      "carrots",
      "garlic",
      "olive oil",
      "parmesan cheese",
      "salt",
      "pepper",
    ],
    instructions: [
      "Cook pasta according to package instructions and drain.",
      "Heat olive oil in a skillet and sauté garlic for 1 minute.",
      "Add chopped vegetables and cook 5-6 minutes until tender-crisp.",
      "Toss cooked pasta with vegetables, sprinkle with parmesan, and season with salt and pepper.",
      "Serve immediately.",
    ],
  },
  {
    id: "58",
    name: "Baked Chicken Legs",
    ingredients: [
      "chicken legs",
      "olive oil",
      "garlic powder",
      "paprika",
      "salt",
      "pepper",
    ],
    instructions: [
      "Preheat oven to 400°F (200°C).",
      "Rub chicken legs with olive oil, garlic powder, paprika, salt, and pepper.",
      "Place on a baking tray and bake for 35-40 minutes until cooked through and skin is crispy.",
      "Serve hot.",
    ],
  },
  {
    id: "59",
    name: "Lentil Soup",
    ingredients: [
      "lentils",
      "carrots",
      "celery",
      "onion",
      "garlic",
      "vegetable broth",
      "cumin",
      "salt",
      "pepper",
      "olive oil",
    ],
    instructions: [
      "Heat olive oil in a pot and sauté onions, garlic, carrots, and celery for 5 minutes.",
      "Add lentils, vegetable broth, and cumin.",
      "Bring to a boil, then simmer for 25-30 minutes until lentils are soft.",
      "Season with salt and pepper and serve hot.",
    ],
  },
  {
    id: "60",
    name: "Pork Fried Rice",
    ingredients: [
      "pork",
      "cooked rice",
      "eggs",
      "peas",
      "carrots",
      "soy sauce",
      "garlic",
      "vegetable oil",
      "green onions",
      "salt",
      "pepper",
    ],
    instructions: [
      "Heat oil in a skillet and sauté minced garlic until fragrant.",
      "Add diced pork and cook until browned.",
      "Push pork to the side, scramble eggs in the pan.",
      "Add cooked rice, peas, and carrots, stir-fry 5 minutes.",
      "Add soy sauce, season with salt and pepper, garnish with green onions, and serve.",
    ],
  },
  {
    id: "61",
    name: "Honey Garlic Chicken",
    ingredients: [
      "chicken breast",
      "honey",
      "garlic",
      "soy sauce",
      "olive oil",
      "salt",
      "pepper",
    ],
    instructions: [
      "Mix honey, minced garlic, and soy sauce in a small bowl to make the sauce.",
      "Season chicken with salt and pepper.",
      "Heat olive oil in a skillet and cook chicken until golden brown on both sides.",
      "Pour sauce over chicken and simmer for 5-7 minutes until cooked through and glazed.",
      "Serve with steamed rice or vegetables.",
    ],
  },
  {
    id: "62",
    name: "Vegetable Quesadilla",
    ingredients: [
      "tortillas",
      "bell peppers",
      "onion",
      "cheddar cheese",
      "olive oil",
      "salt",
      "pepper",
    ],
    instructions: [
      "Heat olive oil in a pan and sauté sliced bell peppers and onions until tender.",
      "Place a tortilla in a skillet over medium heat.",
      "Sprinkle half of the tortilla with cheese and sautéed vegetables, fold over.",
      "Cook 2-3 minutes per side until golden and cheese melts.",
      "Cut into wedges and serve with salsa or sour cream.",
    ],
  },
  {
    id: "63",
    name: "Beef Tacos with Salsa",
    ingredients: [
      "ground beef",
      "taco shells",
      "lettuce",
      "tomatoes",
      "onion",
      "cheddar cheese",
      "salsa",
      "taco seasoning",
      "olive oil",
      "salt",
      "pepper",
    ],
    instructions: [
      "Heat olive oil in a skillet and sauté ground beef with taco seasoning until fully cooked.",
      "Chop lettuce, tomatoes, and onion.",
      "Warm taco shells in oven or pan.",
      "Fill each shell with beef, vegetables, cheese, and top with salsa.",
      "Serve immediately.",
    ],
  },
  {
    id: "64",
    name: "Coconut Shrimp",
    ingredients: [
      "shrimp",
      "coconut flakes",
      "flour",
      "eggs",
      "salt",
      "pepper",
      "oil for frying",
    ],
    instructions: [
      "Peel and devein shrimp, pat dry.",
      "Season flour with salt and pepper.",
      "Dip shrimp in flour, then beaten egg, and coat with coconut flakes.",
      "Heat oil in a skillet and fry shrimp until golden and crispy, 2-3 minutes per side.",
      "Drain on paper towels and serve with dipping sauce.",
    ],
  },
  {
    id: "65",
    name: "Pasta Puttanesca",
    ingredients: [
      "spaghetti",
      "tomatoes",
      "olives",
      "capers",
      "garlic",
      "anchovy fillets",
      "olive oil",
      "red pepper flakes",
      "parsley",
      "salt",
    ],
    instructions: [
      "Cook spaghetti according to package instructions.",
      "Heat olive oil in a pan, sauté garlic, anchovies, and red pepper flakes until fragrant.",
      "Add chopped tomatoes, olives, and capers. Simmer 10 minutes.",
      "Toss cooked spaghetti with sauce and garnish with parsley.",
      "Serve hot.",
    ],
  },
  {
    id: "66",
    name: "Chicken Caesar Wrap",
    ingredients: [
      "chicken breast",
      "tortilla wraps",
      "lettuce",
      "parmesan cheese",
      "caesar dressing",
      "olive oil",
      "salt",
      "pepper",
    ],
    instructions: [
      "Season chicken with salt and pepper and cook in olive oil until golden and cooked through.",
      "Chop lettuce and shred parmesan cheese.",
      "Warm tortillas, spread a layer of caesar dressing.",
      "Add cooked chicken, lettuce, and cheese, then roll up tightly.",
      "Serve immediately.",
    ],
  },
  {
    id: "67",
    name: "Stuffed Mushrooms",
    ingredients: [
      "large mushrooms",
      "cream cheese",
      "garlic",
      "parmesan cheese",
      "breadcrumbs",
      "olive oil",
      "salt",
      "pepper",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "Remove mushroom stems and chop finely.",
      "Sauté stems with garlic in olive oil until soft.",
      "Mix sautéed stems with cream cheese, parmesan, breadcrumbs, salt, and pepper.",
      "Stuff mixture into mushroom caps and bake 15-20 minutes until golden.",
      "Serve hot.",
    ],
  },
  {
    id: "68",
    name: "Teriyaki Beef Skewers",
    ingredients: [
      "beef cubes",
      "soy sauce",
      "honey",
      "garlic",
      "ginger",
      "bell peppers",
      "onion",
      "olive oil",
      "salt",
      "pepper",
    ],
    instructions: [
      "Mix soy sauce, honey, minced garlic, and ginger to make teriyaki sauce.",
      "Thread beef cubes and vegetables alternately onto skewers.",
      "Brush skewers with teriyaki sauce and marinate 30 minutes.",
      "Grill skewers 8-10 minutes, turning occasionally, until beef is cooked to desired doneness.",
      "Serve hot.",
    ],
  },
  {
    id: "69",
    name: "Minestrone Soup",
    ingredients: [
      "carrots",
      "celery",
      "onion",
      "zucchini",
      "tomato paste",
      "cannellini beans",
      "vegetable broth",
      "pasta",
      "garlic",
      "olive oil",
      "salt",
      "pepper",
    ],
    instructions: [
      "Heat olive oil in a large pot and sauté garlic, onions, carrots, and celery 5 minutes.",
      "Add zucchini, tomato paste, beans, and vegetable broth. Simmer 20 minutes.",
      "Add pasta and cook until tender.",
      "Season with salt and pepper and serve hot.",
    ],
  },
  {
    id: "70",
    name: "Greek Chicken Gyros",
    ingredients: [
      "chicken breast",
      "pita bread",
      "tomatoes",
      "onion",
      "cucumber",
      "tzatziki sauce",
      "olive oil",
      "salt",
      "pepper",
      "oregano",
    ],
    instructions: [
      "Season chicken with salt, pepper, and oregano, cook in olive oil until done, slice thinly.",
      "Chop tomatoes, onion, and cucumber.",
      "Warm pita bread and spread tzatziki sauce.",
      "Fill with chicken and vegetables, roll, and serve.",
    ],
  },
  {
    id: "71",
    name: "Shrimp Pad Thai",
    ingredients: [
      "rice noodles",
      "shrimp",
      "eggs",
      "bean sprouts",
      "green onions",
      "peanuts",
      "pad thai sauce",
      "vegetable oil",
      "garlic",
      "lime",
    ],
    instructions: [
      "Cook rice noodles according to package instructions.",
      "Heat oil in a wok, sauté garlic, then add shrimp and cook until pink.",
      "Push shrimp aside, scramble eggs in the wok.",
      "Add noodles, bean sprouts, and pad thai sauce, tossing to combine.",
      "Garnish with peanuts, green onions, and lime wedges.",
    ],
  },
  {
    id: "72",
    name: "Baked Cod with Lemon",
    ingredients: [
      "cod fillets",
      "lemon",
      "butter",
      "garlic",
      "parsley",
      "salt",
      "pepper",
    ],
    instructions: [
      "Preheat oven to 400°F (200°C).",
      "Place cod fillets on a baking sheet, season with salt and pepper.",
      "Top with butter, minced garlic, and lemon slices.",
      "Bake 12-15 minutes until fish is opaque and flakes easily.",
      "Garnish with parsley and serve.",
    ],
  },
  {
    id: "73",
    name: "Vegetable Frittata",
    ingredients: [
      "eggs",
      "milk",
      "spinach",
      "bell peppers",
      "onion",
      "cheese",
      "salt",
      "pepper",
      "olive oil",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "Beat eggs with milk, salt, and pepper.",
      "Sauté vegetables in olive oil until tender.",
      "Pour egg mixture over vegetables, sprinkle cheese on top.",
      "Bake 20-25 minutes until set and golden.",
      "Serve warm.",
    ],
  },
  {
    id: "74",
    name: "Pork Chops with Apples",
    ingredients: [
      "pork chops",
      "apples",
      "onion",
      "butter",
      "olive oil",
      "salt",
      "pepper",
      "thyme",
    ],
    instructions: [
      "Season pork chops with salt and pepper.",
      "Heat olive oil and butter in a skillet, cook pork chops 4-5 minutes per side until golden.",
      "Remove pork and sauté sliced apples and onions with thyme until soft.",
      "Return pork to the pan and heat through.",
      "Serve warm.",
    ],
  },
  {
    id: "75",
    name: "Chicken and Vegetable Stir Fry",
    ingredients: [
      "chicken breast",
      "broccoli",
      "carrots",
      "bell peppers",
      "soy sauce",
      "garlic",
      "ginger",
      "vegetable oil",
      "salt",
      "pepper",
    ],
    instructions: [
      "Slice chicken and vegetables into thin strips.",
      "Heat oil in a wok, cook chicken until golden.",
      "Add garlic and ginger, sauté 1 minute.",
      "Add vegetables and stir-fry 5-6 minutes until tender-crisp.",
      "Add soy sauce, toss well, and serve hot.",
    ],
  },
  {
    id: "76",
    name: "Spinach Lasagna",
    ingredients: [
      "lasagna noodles",
      "spinach",
      "ricotta cheese",
      "mozzarella cheese",
      "tomato sauce",
      "olive oil",
      "garlic",
      "salt",
      "pepper",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "Sauté garlic in olive oil, add spinach until wilted.",
      "Cook lasagna noodles and drain.",
      "Layer noodles, spinach, ricotta, tomato sauce, and mozzarella in a baking dish.",
      "Repeat layers, ending with mozzarella on top.",
      "Bake 35-40 minutes until cheese is golden. Serve hot.",
    ],
  },
  {
    id: "77",
    name: "Mango Chicken Salad",
    ingredients: [
      "chicken breast",
      "mango",
      "lettuce",
      "red onion",
      "avocado",
      "olive oil",
      "lime juice",
      "salt",
      "pepper",
    ],
    instructions: [
      "Cook chicken and slice thinly.",
      "Chop mango, red onion, and avocado.",
      "Toss lettuce with olive oil, lime juice, salt, and pepper.",
      "Top with chicken and fruits. Serve chilled.",
    ],
  },
  {
    id: "78",
    name: "Spicy Tuna Roll",
    ingredients: [
      "sushi rice",
      "nori sheets",
      "tuna",
      "sriracha",
      "mayonnaise",
      "cucumber",
      "soy sauce",
    ],
    instructions: [
      "Mix tuna with mayonnaise and sriracha.",
      "Place nori sheet on bamboo mat, spread sushi rice evenly.",
      "Place tuna mixture and cucumber slices, then roll tightly.",
      "Cut into pieces and serve with soy sauce.",
    ],
  },
  {
    id: "79",
    name: "Baked Sweet Potatoes",
    ingredients: [
      "sweet potatoes",
      "olive oil",
      "salt",
      "pepper",
      "butter",
      "honey",
    ],
    instructions: [
      "Preheat oven to 400°F (200°C).",
      "Scrub sweet potatoes, prick with fork.",
      "Rub with olive oil, salt, and pepper.",
      "Bake 45-50 minutes until tender.",
      "Split open, add butter and drizzle with honey.",
    ],
  },
  {
    id: "80",
    name: "Chicken and Rice Casserole",
    ingredients: [
      "chicken breast",
      "rice",
      "cream of mushroom soup",
      "cheddar cheese",
      "onion",
      "garlic",
      "vegetable broth",
      "salt",
      "pepper",
      "olive oil",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "Sauté onion and garlic in olive oil until soft.",
      "Add diced chicken and cook until lightly browned.",
      "In a baking dish, mix chicken, rice, soup, broth, and seasonings.",
      "Top with cheddar cheese and bake 35-40 minutes until rice is cooked and cheese is melted.",
      "Serve hot.",
    ],
  },
 
  {
    id: "81",
    name: "Beef Stroganoff",
    ingredients: ["beef strips", "mushrooms", "onion", "garlic", "sour cream", "beef broth", "flour", "butter", "olive oil", "salt", "pepper", "egg noodles"],
    instructions: [
      "Cook egg noodles according to package instructions and set aside.",
      "Heat olive oil and butter in a skillet, sauté onions and garlic until soft.",
      "Add beef strips, cook until browned, remove and set aside.",
      "Add mushrooms and cook 5 minutes.",
      "Sprinkle flour, stir, then add beef broth, simmer 5 minutes until thickened.",
      "Return beef to skillet, stir in sour cream, season with salt and pepper.",
      "Serve hot over noodles."
    ]
  },
  {
    id: "82",
    name: "Garlic Butter Shrimp Pasta",
    ingredients: ["shrimp", "spaghetti", "garlic", "butter", "olive oil", "parsley", "salt", "pepper", "lemon"],
    instructions: [
      "Cook spaghetti according to package instructions and drain.",
      "Heat olive oil and butter in a pan, sauté garlic 1 minute.",
      "Add shrimp and cook until pink.",
      "Toss in cooked pasta, season with salt and pepper.",
      "Garnish with parsley and lemon juice before serving."
    ]
  },
  {
    id: "83",
    name: "Buffalo Chicken Wings",
    ingredients: ["chicken wings", "hot sauce", "butter", "garlic powder", "salt", "pepper", "oil for frying"],
    instructions: [
      "Season chicken wings with salt, pepper, and garlic powder.",
      "Heat oil in a deep fryer or pan, fry wings until crispy and golden.",
      "Melt butter and mix with hot sauce to make buffalo sauce.",
      "Toss fried wings in buffalo sauce and serve with celery sticks."
    ]
  },
  {
    id: "84",
    name: "Quinoa Salad",
    ingredients: ["quinoa", "cucumber", "tomatoes", "red onion", "feta cheese", "olive oil", "lemon juice", "salt", "pepper", "parsley"],
    instructions: [
      "Cook quinoa according to package instructions and let cool.",
      "Chop cucumber, tomatoes, and red onion.",
      "Mix quinoa with vegetables, feta, olive oil, and lemon juice.",
      "Season with salt and pepper, garnish with parsley, and serve."
    ]
  },
  {
    id: "85",
    name: "Pesto Pasta",
    ingredients: ["pasta", "basil pesto", "parmesan cheese", "olive oil", "salt", "pepper", "pine nuts (optional)"],
    instructions: [
      "Cook pasta according to package instructions and drain.",
      "Toss pasta with basil pesto and a drizzle of olive oil.",
      "Season with salt and pepper.",
      "Top with parmesan cheese and pine nuts if desired."
    ]
  },
  {
    id: "86",
    name: "Teriyaki Chicken Bowl",
    ingredients: ["chicken breast", "rice", "broccoli", "carrots", "teriyaki sauce", "olive oil", "salt", "pepper"],
    instructions: [
      "Cook rice according to package instructions.",
      "Season chicken with salt and pepper, cook in olive oil until golden and cooked through.",
      "Steam broccoli and carrots until tender.",
      "Slice chicken and serve over rice with vegetables.",
      "Drizzle teriyaki sauce on top before serving."
    ]
  },
  {
    id: "87",
    name: "Mushroom Risotto with Peas",
    ingredients: ["arborio rice", "mushrooms", "peas", "onion", "garlic", "vegetable broth", "parmesan cheese", "butter", "olive oil", "salt", "pepper"],
    instructions: [
      "Heat olive oil in a pan, sauté onions and garlic until soft.",
      "Add mushrooms and cook until tender.",
      "Add rice and toast 2 minutes.",
      "Gradually add vegetable broth, stirring constantly until rice is creamy and cooked.",
      "Stir in peas, butter, and parmesan cheese, season with salt and pepper."
    ]
  },
  {
    id: "88",
    name: "Chicken Fajitas",
    ingredients: ["chicken breast", "bell peppers", "onion", "tortillas", "olive oil", "chili powder", "cumin", "salt", "pepper", "lime"],
    instructions: [
      "Slice chicken and vegetables into thin strips.",
      "Season chicken with chili powder, cumin, salt, and pepper.",
      "Heat olive oil in a skillet, cook chicken until browned.",
      "Add vegetables and sauté until tender-crisp.",
      "Serve with warm tortillas and a squeeze of lime."
    ]
  },
  {
    id: "89",
    name: "Caprese Pasta Salad",
    ingredients: ["pasta", "cherry tomatoes", "mozzarella balls", "basil", "olive oil", "balsamic glaze", "salt", "pepper"],
    instructions: [
      "Cook pasta according to package instructions and drain.",
      "Halve cherry tomatoes and combine with mozzarella balls and fresh basil.",
      "Toss pasta with olive oil, add tomato mixture, season with salt and pepper.",
      "Drizzle balsamic glaze on top before serving."
    ]
  },
  {
    id: "90",
    name: "Lemon Garlic Tilapia",
    ingredients: ["tilapia fillets", "lemon", "garlic", "butter", "olive oil", "parsley", "salt", "pepper"],
    instructions: [
      "Preheat oven to 400°F (200°C).",
      "Place tilapia on a baking sheet, season with salt and pepper.",
      "Top with minced garlic, butter, and lemon slices.",
      "Bake 10-12 minutes until fish flakes easily.",
      "Garnish with parsley and serve hot."
    ]
  },
  {
    id: "91",
    name: "Chicken Alfredo",
    ingredients: ["fettuccine pasta", "chicken breast", "heavy cream", "parmesan cheese", "garlic", "butter", "olive oil", "salt", "pepper"],
    instructions: [
      "Cook fettuccine according to package instructions.",
      "Season chicken with salt and pepper, cook in olive oil until golden and cooked through.",
      "In a pan, melt butter, sauté garlic, add heavy cream and simmer 5 minutes.",
      "Add parmesan cheese and stir until sauce thickens.",
      "Toss pasta and chicken with sauce and serve hot."
    ]
  },
  {
    id: "92",
    name: "Greek Salad with Chicken",
    ingredients: ["chicken breast", "lettuce", "cucumber", "tomatoes", "feta cheese", "olives", "olive oil", "lemon juice", "oregano", "salt", "pepper"],
    instructions: [
      "Cook chicken, season with salt and pepper, slice thinly.",
      "Chop lettuce, cucumber, and tomatoes.",
      "Combine vegetables with feta, olives, olive oil, lemon juice, and oregano.",
      "Top salad with chicken slices and serve."
    ]
  },
  {
    id: "93",
    name: "Baked Ziti",
    ingredients: ["ziti pasta", "ground beef", "tomato sauce", "ricotta cheese", "mozzarella cheese", "onion", "garlic", "olive oil", "salt", "pepper"],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "Cook ziti according to package instructions.",
      "Heat olive oil, sauté onion and garlic, add ground beef until browned.",
      "Stir in tomato sauce, season with salt and pepper.",
      "In a baking dish, layer pasta, ricotta, meat sauce, and mozzarella.",
      "Bake 25-30 minutes until cheese is melted and golden."
    ]
  },
  {
    id: "94",
    name: "Vegetable Curry",
    ingredients: ["potatoes", "carrots", "peas", "onion", "garlic", "curry powder", "coconut milk", "olive oil", "salt", "pepper"],
    instructions: [
      "Heat olive oil, sauté onion and garlic until soft.",
      "Add diced potatoes and carrots, cook 5 minutes.",
      "Add curry powder, peas, and coconut milk, simmer 15 minutes until vegetables are tender.",
      "Season with salt and pepper and serve hot."
    ]
  },
  {
    id: "95",
    name: "BBQ Pulled Chicken Sandwich",
    ingredients: ["chicken breast", "bbq sauce", "bread rolls", "coleslaw", "onion", "salt", "pepper"],
    instructions: [
      "Cook chicken in bbq sauce until tender.",
      "Shred chicken with forks.",
      "Toast bread rolls lightly.",
      "Fill rolls with pulled chicken, top with coleslaw and sliced onion.",
      "Serve warm."
    ]
  },
  {
    id: "96",
    name: "Eggplant Parmesan Pasta",
    ingredients: ["pasta", "eggplant", "tomato sauce", "parmesan cheese", "mozzarella cheese", "flour", "egg", "breadcrumbs", "olive oil", "salt", "pepper"],
    instructions: [
      "Slice eggplant, season, dredge in flour, egg, and breadcrumbs, then fry until golden.",
      "Cook pasta according to package instructions.",
      "Toss pasta with tomato sauce, top with fried eggplant, parmesan, and mozzarella.",
      "Bake 15 minutes until cheese melts and serve hot."
    ]
  },
  {
    id: "97",
    name: "Thai Red Curry with Chicken",
    ingredients: ["chicken breast", "red curry paste", "coconut milk", "bell peppers", "onion", "basil", "rice", "olive oil", "salt", "pepper"],
    instructions: [
      "Cook rice according to package instructions.",
      "Heat olive oil, sauté chicken until browned.",
      "Add red curry paste, cook 1 minute, then stir in coconut milk.",
      "Add bell peppers and onions, simmer 10 minutes.",
      "Garnish with basil and serve over rice."
    ]
  },
  {
    id: "98",
    name: "Baked Mac and Cheese",
    ingredients: ["macaroni", "cheddar cheese", "mozzarella cheese", "milk", "butter", "flour", "breadcrumbs", "salt", "pepper"],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "Cook macaroni according to package instructions.",
      "Make a roux: melt butter, whisk in flour, cook 1 minute, add milk slowly until thickened.",
      "Stir in cheese until melted, mix with cooked macaroni.",
      "Place in baking dish, top with breadcrumbs and extra cheese.",
      "Bake 20 minutes until golden and bubbly."
    ]
  },
  {
    id: "99",
    name: "Chicken Teriyaki Skewers",
    ingredients: ["chicken breast", "soy sauce", "honey", "garlic", "ginger", "bell peppers", "onion", "olive oil", "salt", "pepper"],
    instructions: [
      "Mix soy sauce, honey, garlic, and ginger to make teriyaki sauce.",
      "Cut chicken and vegetables into cubes, thread onto skewers.",
      "Brush skewers with sauce and marinate 30 minutes.",
      "Grill or bake until chicken is cooked through, 10-12 minutes.",
      "Serve with remaining sauce."
    ]
  },
  {
    id: "100",
    name: "Vegetable Fried Rice",
    ingredients: ["cooked rice", "carrots", "peas", "bell peppers", "onion", "soy sauce", "garlic", "eggs", "olive oil", "salt", "pepper", "green onions"],
    instructions: [
      "Heat olive oil in a wok, sauté garlic and onion until fragrant.",
      "Add chopped vegetables and cook 3-4 minutes.",
      "Push vegetables aside, scramble eggs in the wok.",
      "Add cooked rice and soy sauce, toss well.",
      "Season with salt and pepper, garnish with green onions, and serve hot."
    ]
  }
];

export const allIngredients = [
  "chicken",
  "pasta",
  "garlic",
  "olive oil",
  "parmesan",
  "tomatoes",
  "onion",
  "basil",
  "cream",
  "broccoli",
  "carrots",
  "soy sauce",
  "ginger",
  "rice",
  "ground beef",
  "taco shells",
  "lettuce",
  "cheese",
  "salsa",
  "mushrooms",
  "white wine",
  "feta",
  "olives",
  "salmon",
  "lemon",
  "butter",
  "eggs",
  "peas",
  "pizza dough",
  "mozzarella",
  "curry powder",
  "bread",
  "maple syrup",
  "shrimp",
  "balsamic vinegar",
  "chocolate chips",
  "pork",
  "bbq sauce",
  "coleslaw",
  "caesar dressing",
  "green curry paste",
  "spinach",
  "pie crust",
  "honey",
  "tortillas",
  "red onion",
  "cheddar cheese",
  "capers",
  "anchovy fillets",
  "red pepper flakes",
  "parsley",
  "cilantro",
  "cucumber",
  "tzatziki sauce",
  "bean sprouts",
  "green onions",
  "peanuts",
  "lime",
  "cannellini beans",
  "zucchini",
  "pita bread",
  "rice noodles",
  "pasta sauce",
  "arborio rice",
  "heavy cream",
  "ricotta cheese",
  "spinach",
  "potatoes",
  "bell peppers",
  "chili powder",
  "cumin",
  "balsamic glaze",
  "tilapia fillets",
  "egg noodles",
  "sour cream",
  "flour",
  "breadcrumbs",
  "eggplant",
  "red curry paste",
  "macaroni",
  "milk",
  "green peas",
  "thyme",
  "vegetable broth",
  "vegetable oil",
  "oregano",
  "sriracha",
  "mayonnaise",
  "cinnamon",
  "pine nuts"
];
